app = "todo-list-app-backend"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  ConnectionStrings__DefaultConnection = "Server=tcp:seu-servidor.database.windows.net,1433;Initial Catalog=nome-do-seu-banco;Persist Security Info=False;User ID=seu-usuario;Password=sua-senha;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

[http_service]
  internal_port = 5000
  processes = ["app"]

[processes]
  [process.app]
    command = "dotnet todo-list.dll"
